#!/usr/bin/env bash

# Define an associative array:
typeset -A mode
# And its content:
mode=(
  [Desktop]="autorandr --load desktop"
  [Laptop]="autorandr --load laptop"
  [Test Mode]="autorandr --load testmode"
  [Cancel]=""
)

mode_nrows=${#mode[@]}

selected="$(printf '%s\n' "${!mode[@]}" | sort | rofi -dmenu -p "Monitor setup" -i -lines 2)"
i3-msg -q "exec --no-startup-id ${mode[${selected}]}"
