[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 7

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
#command = "tuigreet --remember --remember-session --greeting 'Welcome Space Cowboy' --cmd sway --theme 'border=white;text=white;prompt=green;time=green;action=blue;button=yellow;container=gray;input=white'"
# if using wlgreet
#command = "sway --config /etc/greetd/sway-config"
command = "sway -c /etc/nwg-hello/sway-config"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greetd"
